include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
    unused_import: error
    unused_local_variable: warning
    dead_code: error

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - only_throw_errors
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
