// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71xdWj_-s8CjVhm-nwnUdqsbETpIqV3c',
    appId: '1:684955196888:web:6869ff112857b2b548a6ad',
    messagingSenderId: '684955196888',
    projectId: 'sana-muslim',
    authDomain: 'sana-muslim.firebaseapp.com',
    storageBucket: 'sana-muslim.firebasestorage.app',
    measurementId: 'G-S6MLVQ9Z4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAiEbYk9eX-yJ618PDA3C7H1TCcQ3Vmg',
    appId: '1:684955196888:android:8bad283a118b355a48a6ad',
    messagingSenderId: '684955196888',
    projectId: 'sana-muslim',
    storageBucket: 'sana-muslim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--K7rw-_RZG0hngJYimwVwrc4bPNNOBo',
    appId: '1:684955196888:ios:e618fadcb5651a1148a6ad',
    messagingSenderId: '684955196888',
    projectId: 'sana-muslim',
    storageBucket: 'sana-muslim.firebasestorage.app',
    iosBundleId: 'com.korya.muslimapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--K7rw-_RZG0hngJYimwVwrc4bPNNOBo',
    appId: '1:684955196888:ios:17c231f9e551ac1b48a6ad',
    messagingSenderId: '684955196888',
    projectId: 'sana-muslim',
    storageBucket: 'sana-muslim.firebasestorage.app',
    iosBundleId: 'com.example.muslimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC71xdWj_-s8CjVhm-nwnUdqsbETpIqV3c',
    appId: '1:684955196888:web:e52b5f797112bf0748a6ad',
    messagingSenderId: '684955196888',
    projectId: 'sana-muslim',
    authDomain: 'sana-muslim.firebaseapp.com',
    storageBucket: 'sana-muslim.firebasestorage.app',
    measurementId: 'G-SKN1DHB2J6',
  );
}
