// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK0k_QEZlTmGZDKBQIQPVjbLe2n_qJswQ',
    appId: '1:819076330770:web:6598fd9eaf0d549fd3efcb',
    messagingSenderId: '819076330770',
    projectId: 'sana-3f290',
    authDomain: 'sana-3f290.firebaseapp.com',
    storageBucket: 'sana-3f290.firebasestorage.app',
    measurementId: 'G-EL0HK14W1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCorYrARM6GEplSXVn6rxxRrUCALT3sem4',
    appId: '1:819076330770:android:77c237894f20f04ed3efcb',
    messagingSenderId: '819076330770',
    projectId: 'sana-3f290',
    storageBucket: 'sana-3f290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWvP5-fPi_pQF4TZUKss0IE313SlFJGXo',
    appId: '1:819076330770:ios:12e4786bff412c85d3efcb',
    messagingSenderId: '819076330770',
    projectId: 'sana-3f290',
    storageBucket: 'sana-3f290.firebasestorage.app',
    iosBundleId: 'com.korya.muslimapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWvP5-fPi_pQF4TZUKss0IE313SlFJGXo',
    appId: '1:819076330770:ios:e9241bd5adb21191d3efcb',
    messagingSenderId: '819076330770',
    projectId: 'sana-3f290',
    storageBucket: 'sana-3f290.firebasestorage.app',
    iosBundleId: 'com.example.muslimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK0k_QEZlTmGZDKBQIQPVjbLe2n_qJswQ',
    appId: '1:819076330770:web:4ac76c5287705158d3efcb',
    messagingSenderId: '819076330770',
    projectId: 'sana-3f290',
    authDomain: 'sana-3f290.firebaseapp.com',
    storageBucket: 'sana-3f290.firebasestorage.app',
    measurementId: 'G-0KFHFT9XYM',
  );
}
