name: Android Shorebird Patch

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  android_patch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Shorebird CLI
        uses: shorebirdtech/setup-shorebird@v1

      - name: Restore Keystore File
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > new-release-key.jks

      - name: Restore Firebase Config
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > lib/core/services/firebase/firebase_options.dart

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../new-release-key.jks" >> android/key.properties

      - name: Install Dependencies
        run: flutter pub get

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          working-directory: android

      - name: Install Bundler and Gems
        working-directory: android
        run: |
          gem install bundler
          bundle install

      - name: Shorebird Patch
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
          ADMIN_PIN: ${{ secrets.ADMIN_PIN }}
        run: bundle exec fastlane shorebird_patch
